version: '3'
services:
  backend:
    build: ./backendNodeJS
    environment:
      - PORT=5000
      - PYTHON_SERVER_URL=http://python:5001
    env_file:
      - .env
    ports:
      - 5000:5000
  frontend:
    build: ./frontend
    environment:
      - REACT_APP_BACKEND_URI=http://aaron-fyp-api.ecread.info
    env_file:
      - .env
    ports:
      - 3000:80
  python:
    build: ./python/project
    environment:
      - PORT=5001
    env_file:
      - .env
  
