version: '3'
services:
  backend:
    build: ./backendNodeJS
    enironment:
      - PORT=5000
    env_file:
      - .env
    ports:
      - 5000:5000
  frontend:
    build: ./frontend
    environment:
      - REACT_APP_BACKEND_URI="http://aaron-fyp-api.ecread.info"
    env_file:
      - .env
    ports:
      - 80:3000
  python:
    build: ./pytnon/project
    environment:
      - PORT=5001
    env_file:
      - .env
    ports:
      - 5001:5001
  
